// Code generated by protoc-gen-go.
// source: until.proto
// DO NOT EDIT!

/*
Package conn is a generated protocol buffer package.

It is generated from these files:
	until.proto

It has these top-level messages:
	C2SAction
	Coordinate
	Logic
	S2CSelfInfo
	S2CClientInfo
	S2CDeleteClient
*/
package conn

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type C2SAction struct {
	Action           *string `protobuf:"bytes,2,req" json:"Action,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2SAction) Reset()         { *m = C2SAction{} }
func (m *C2SAction) String() string { return proto.CompactTextString(m) }
func (*C2SAction) ProtoMessage()    {}

func (m *C2SAction) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

type Coordinate struct {
	X                *int32 `protobuf:"varint,1,req" json:"X,omitempty"`
	Y                *int32 `protobuf:"varint,2,req" json:"Y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}

func (m *Coordinate) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Coordinate) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type Logic struct {
	Position         *Coordinate `protobuf:"bytes,1,req" json:"Position,omitempty"`
	Color            *string     `protobuf:"bytes,2,req" json:"Color,omitempty"`
	Name             *string     `protobuf:"bytes,3,req" json:"Name,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Logic) Reset()         { *m = Logic{} }
func (m *Logic) String() string { return proto.CompactTextString(m) }
func (*Logic) ProtoMessage()    {}

func (m *Logic) GetPosition() *Coordinate {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Logic) GetColor() string {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return ""
}

func (m *Logic) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type S2CSelfInfo struct {
	CanvasWidth      *int32 `protobuf:"varint,2,req" json:"CanvasWidth,omitempty"`
	CanvasHeight     *int32 `protobuf:"varint,3,req" json:"CanvasHeight,omitempty"`
	Clients          *Logic `protobuf:"bytes,4,req" json:"Clients,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2CSelfInfo) Reset()         { *m = S2CSelfInfo{} }
func (m *S2CSelfInfo) String() string { return proto.CompactTextString(m) }
func (*S2CSelfInfo) ProtoMessage()    {}

func (m *S2CSelfInfo) GetCanvasWidth() int32 {
	if m != nil && m.CanvasWidth != nil {
		return *m.CanvasWidth
	}
	return 0
}

func (m *S2CSelfInfo) GetCanvasHeight() int32 {
	if m != nil && m.CanvasHeight != nil {
		return *m.CanvasHeight
	}
	return 0
}

func (m *S2CSelfInfo) GetClients() *Logic {
	if m != nil {
		return m.Clients
	}
	return nil
}

type S2CClientInfo struct {
	Clients          []*Logic `protobuf:"bytes,2,rep" json:"Clients,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *S2CClientInfo) Reset()         { *m = S2CClientInfo{} }
func (m *S2CClientInfo) String() string { return proto.CompactTextString(m) }
func (*S2CClientInfo) ProtoMessage()    {}

func (m *S2CClientInfo) GetClients() []*Logic {
	if m != nil {
		return m.Clients
	}
	return nil
}

type S2CDeleteClient struct {
	Name             *string `protobuf:"bytes,2,req" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2CDeleteClient) Reset()         { *m = S2CDeleteClient{} }
func (m *S2CDeleteClient) String() string { return proto.CompactTextString(m) }
func (*S2CDeleteClient) ProtoMessage()    {}

func (m *S2CDeleteClient) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}
